### ISSUE TITLE
Docker Hub 里面的镜像版本，更新后内容无变化

### ISSUE THREAD

**Issue by Mydong** [zmlix/chatgpt-web#3]
重新拉取了镜像，但是发现 21号，22号更新的内容，在拉取的docker版本上并没有体现；
另外一台服务器部署了，发现也是这个情况；
运行命令如下：

```
docker stop chatgpt-web && docker rm chatgpt-web
docker run --name chatgpt-web --rm -it -p 5200:5200 -d loewe24/chatgpt-web:latest
```

![image](https://user-images.githubusercontent.com/14023137/226792748-a4a6b0d9-e3d9-4355-aa39-493b143bef4e.png)

**Comment by zmlix** [comment]
镜像更新了，你重新pull一下试试

**Comment by zmlix** [comment]
有时候不会及时更新镜像，如果你要最新的功能，可以从GitHub拉代码自己构建

**Comment by Mydong** [comment]
> 有时候不会及时更新镜像，如果你要最新的功能，可以从GitHub拉代码自己构建

好的好的 谢谢哈
