### ISSUE TITLE
[BUG] Prompt 商城中的一些提示有误，会导致回复的结果是错误的!

### ISSUE THREAD

**Issue by Mydong** [zmlix/chatgpt-web#4]
![image](https://user-images.githubusercontent.com/14023137/227416741-6c96edeb-ebd9-4b25-9793-b58862f4f4a9.png)

类似这几个，前面多了 ***替代*：语法，谷歌翻译 >
这样的话，会导致，直接使用，回复出现错误 。 

估计这几个特殊，提取的时候，将示例的字符加进来了
![image](https://user-images.githubusercontent.com/14023137/227417606-ebee0c39-75ee-4f2b-8b0b-03a9f06ee0a9.png)

![image](https://user-images.githubusercontent.com/14023137/227417277-5915eb46-ce81-468d-9de3-a4f968e7815b.png)

**Comment by zmlix** [comment]
目前所有prompt来自这个项目https://github.com/PlexPt/awesome-chatgpt-prompts-zh/blob/main/prompts-zh.json
我是直接使用的，我觉得这确实是个问题，你可以向他们提个issue，我这里可以先加一个过滤。

**Comment by Mydong** [comment]
> 目前所有prompt来自这个项目https://github.com/PlexPt/awesome-chatgpt-prompts-zh/blob/main/prompts-zh.json
> 我是直接使用的，我觉得这确实是个问题，你可以向他们提个issue，我这里可以先加一个过滤。

好的啊  我也提一下  看看会不会修复。

**Comment by Mydong** [comment]
> 目前所有prompt来自这个项目https://github.com/PlexPt/awesome-chatgpt-prompts-zh/blob/main/prompts-zh.json 我是直接使用的，我觉得这确实是个问题，你可以向他们提个issue，我这里可以先加一个过滤。

他们说 晚点会修复了。  搞定 解决。

**Comment by zmlix** [comment]
谢谢🥳

**Comment by Mydong** [comment]
> 谢谢🥳

您客气了  谢谢你的项目  用着很舒服；
