### ISSUE TITLE
html语句渲染Bug

### ISSUE THREAD

**Issue by chaoyu1999** [zmlix/chatgpt-web#5]
![QQ截图20230402102943](https://user-images.githubusercontent.com/46945475/229327946-27f0965c-22d3-4727-9486-8ccf6ae12b20.png)
输入html标签时，在上面消息框中html不是以纯文本形式展示，而是被渲染成html页面元素。

**Comment by zmlix** [comment]
这个只要关闭渲染就可以了，不过是否要对用户输入的内容或者html代码进行渲染确实需要考虑一下，因为会有一定的安全风险

**Comment by chaoyu1999** [comment]
> 这个只要关闭渲染就可以了，不过是否要对用户输入的内容或者html代码进行渲染确实需要考虑一下，因为会有一定的安全风险

确实，这有点类似于后端的sql注入。老哥可以考虑优化一下
![3336F40D](https://user-images.githubusercontent.com/46945475/229349412-fa221010-7da4-4cac-a54b-fca48d3707d9.png)

**Comment by zmlix** [comment]
已增加防XSS攻击😀

**Comment by chaoyu1999** [comment]
> XSS攻击

牛哇，老哥
![0A909402](https://user-images.githubusercontent.com/46945475/230252797-8ec17c0f-e0a9-465a-a0da-bdf796175e64.png)
