### ISSUE TITLE
请问从docker拉取镜像,是如何设定代理的?

### ISSUE THREAD

**Issue by AtomRun-Code** [zmlix/chatgpt-web#6]
在下愚笨知道从源码部署是可以修改env.js文件,可是看了半天axios的代理格式都不知道怎么修改.

无耐之下就通过作者提供的docker来试试吧!

主机是可以强国冲浪的,但是部署出来的镜像却是工作不了的.

##### 向作者请教一下.以下是我家软路由情况:

arm/v7的32位系统.能跑OPENWRT,

如若把Chatgpt-web运行于OPENWRT里.

会有一些问题:

第一是32位的系统.

第二是arm的架构,安装不了18以上的nodejs.

##### 那为了跳过这些,也希望能懒个极致,不研究axios.

现在能在我软路由上跑起来的只有:https://hub.docker.com/r/dockercommo/chatgpt-web

是的,很对不起,尽管是使用了作者的劳动成果,却也没有在您官方的任何渠道进行调用,还厚着个脸皮来咨询相关问题.

关于本人的使用情况,尽管作者还没回答,在下也先表感谢,毕竟是你的源动力,让docker上的dockercommo大哥转换成了arm32bit.

才让我看到了在我的机器上运行的一丝阳光.Thank's for zmlix  & dockercommo!

**Comment by zmlix** [comment]
你太客气了，我没有玩过OPENWRT，所以不太清楚你的问题，但是如果需要代理，你或许可以在OPENWRT上运行一个openai的反向代理，然后在前端填入这个本机的反向代理地址就可以使用了，GitHub有很多openai反代的开源项目，你可以找一个合适的试一试😀。

**Comment by AtomRun-Code** [comment]
> 你太客气了，我没有玩过OPENWRT，所以不太清楚你的问题，但是如果需要代理，你或许可以在OPENWRT上运行一个openai的反向代理，然后在前端填入这个本机的反向代理地址就可以使用了，GitHub有很多openai反代的开源项目，你可以找一个合适的试一试😀。

感谢您的回复，我就是个不懂行，还爱玩的。您的回复我看明白了。我先尝试一下这种新的方式。

**Comment by AtomRun-Code** [comment]
😂逛了一圈，24小时没睡过，没有一个看得懂的。🤣
