### ISSUE TITLE
Prompt商城不可用

### ISSUE THREAD

**Issue by codermq** [zmlix/chatgpt-web#8]
检查后是因为访问不到程序内置的prompts-zh.json，然后我使用我自己的代理手动可以打开`prompts-zh.json`页面，但是替换到程序`api.js`文件里面，还是访问不到，报的错误是 ![报错]( https://git.7ni.cc/codermq/image/blob/main/Test/1_8io8rp_.jpeg?raw=true) 
 ![报错](  https://git.7ni.cc/codermq/image/blob/main/Test/Snipaste_2023-04-25_14-10-04_idy9vk_.jpeg?raw=true)

**Comment by Mydong** [comment]
确实 这个出问题了 
![image](https://user-images.githubusercontent.com/14023137/234239476-fb98fdfb-79cc-481a-a07a-077f9434ec22.png)

**Comment by codermq** [comment]
这个要如何解决呢，附上我自己的代理，能访问`https://git.7ni.cc/PlexPt/awesome-chatgpt-prompts-zh/blob/main/prompts-zh.json`

**Comment by zmlix** [comment]
😱我晚上看一下

**Comment by zmlix** [comment]
> 这个要如何解决呢，附上我自己的代理，能访问`https://git.7ni.cc/PlexPt/awesome-chatgpt-prompts-zh/blob/main/prompts-zh.json`

我看了一下没问题，你检查一下网络，还有你应该使用`https://git.7ni.cc/PlexPt/awesome-chatgpt-prompts-zh/raw/main/prompts-zh.json`这个打开raw文件的网址

**Comment by zmlix** [comment]
> 确实 这个出问题了 ![image](https://user-images.githubusercontent.com/14023137/234239611-750b615f-a2ee-42f1-87c5-8f5f937bd737.png)

不能访问重定向的链接，你检查一下使用的链接是否重定向了

**Comment by Mydong** [comment]
> > 确实 这个出问题了 ![image](https://user-images.githubusercontent.com/14023137/234239611-750b615f-a2ee-42f1-87c5-8f5f937bd737.png)
> 
> 不能访问重定向的链接，你检查一下使用的链接是否重定向了

可以了  不知道怎么滴  今天刷新了一下 又ok了😂  可能昨天是我代理的问题

**Comment by codermq** [comment]
可以了 使用`https://git.7ni.cc/PlexPt/awesome-chatgpt-prompts-zh/raw/main/prompts-zh.json`，这个地址就可以获取到了 感谢！
