### ISSUE TITLE
查询余额的接口依然存在点问题 + 一个BUG反馈

### ISSUE THREAD

**Issue by Mydong** [zmlix/chatgpt-web#9]
![image](https://user-images.githubusercontent.com/14023137/234784937-6825c3fc-88f0-463e-9b7a-495e97a18f99.png)
一直显示查询失败，最开始以为是需要挂梯子，后来发现，挂梯子也没用；
新的查询余额接口好像是这个；
https://api.openai.com/v1/billing/credits

以下是GPT回复的：
That's correct! The API endpoint for querying OpenAI account balance is indeed "https://api.openai.com/v1/billing/credits". The other URL you provided, "https://api.openai.com/dashboard/billing/credit_grants", is for viewing credit grants history and not for querying account balance.

To use this API endpoint, you need to include your OpenAI API key in the Authorization header of your request. Here's an example of how you could do that using cURL:

```
curl --location --request GET 'https://api.openai.com/v1/billing/credits' \
--header 'Authorization: Bearer YOUR_API_KEY_HERE'

```
This will return a JSON response containing information about your OpenAI account balance.

**Comment by zmlix** [comment]
确实有这个问题

**Comment by zmlix** [comment]
已修复

**Comment by Mydong** [comment]
哈哈哈   完美

**Comment by Mydong** [comment]
@zmlix  作者，余额查询的接口好像还是有点问题。会一直提示这个
![image](https://github.com/zmlix/chatgpt-web/assets/14023137/41bc41bf-7512-4e5f-92f3-f25f728865df)

另外，最近使用一键功能搭建了这个项目，这里面的余额功能是正常的；
https://github.com/Yidadaa/ChatGPT-Next-Web   作者瞅瞅

**Comment by zmlix** [comment]
最近比较忙😂，现在已经去掉了字数限制😀

**Comment by Mydong** [comment]
> 最近比较忙😂，现在已经去掉了字数限制😀

哈哈哈 棒😊
